apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-svc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber-svc-deployment
  template:
    metadata:
      labels:
        app: subscriber-svc-deployment
    spec:
      containers:
      - name: subscriber-svc-deployment
        image: dtfernando/subscriber_preprocessor:latest
        imagePullPolicy: Always
        env:
          - name: AD_URL
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: AD_URL
          - name: MDI_URL
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: MDI_URL
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
      nodeName: worker3